trigger: 
- main
- features/*

pool: asr

variables: 
  ranjeet: '$(System.DefaultWorkingDirectory)/env/dev'
  anup_service_connection: 'svc'

stages: 
 - stage: install_stage
   jobs:
     - job: terraform_install
       displayName: install
       steps:
       - task: TerraformInstaller@1
         inputs:
           terraformVersion: 'latest'
     - job: terraform_init
       displayName: init
       steps:
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: $(ranjeet)
           backendServiceArm: $(anup_service_connection)
           backendAzureRmResourceGroupName: 'for-backend'
           backendAzureRmStorageAccountName: 'pipelinekeliye'
           backendAzureRmContainerName: 'pipestorage'
           backendAzureRmKey: 'pttr.tfstate'
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: $(ranjeet)
           environmentServiceNameAzureRM: $(anup_service_connection)