trigger: 
- main
- features/*

pool: asr

variables: 
  ranjeet: '$(System.DefaultWorkingDirectory)/env/${{parameters.environment}}'
  anup_service_connection: 'svc'

parameters:
 - name: environment
   displayName: environment_(dev/prod)
   default: prod
   type: string
   values:
     - dev
     - prod


stages: 
 - stage: install_stage
   jobs:
     - job: terraform_install
       displayName: install
       steps:
       - task: TerraformInstaller@1
         inputs:
           terraformVersion: 'latest'
     - job: terraform_init_plan
       dependsOn: terraform_install
       
       displayName: init
       steps:
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: $(ranjeet)
           backendServiceArm: $(anup_service_connection)
           backendAzureRmResourceGroupName: 'for-backend'
           backendAzureRmStorageAccountName: 'pipelinekeliye'
           backendAzureRmContainerName: 'pipestorage'
           backendAzureRmKey: 'pttr.tfstate'
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: $(ranjeet)
           environmentServiceNameAzureRM: $(anup_service_connection)

     - job: Manual_validation
       displayName: Manual_validation
       pool: server
       dependsOn: terraform_init_plan
       timeoutInMinutes: 1
       condition: succeeded('terraform_init_plan')
       steps:
       - task: ManualValidation@1
         inputs:
           notifyUsers: 'Ranjeet'
           approvers: 'anup@vaishalikahakar91outlook.onmicrosoft.com'

     - job: Terraform_Apply
       displayName: apply
       dependsOn: Manual_validation
       steps:
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: $(ranjeet)
           backendServiceArm: $(anup_service_connection)
           backendAzureRmResourceGroupName: 'for-backend'
           backendAzureRmStorageAccountName: 'pipelinekeliye'
           backendAzureRmContainerName: 'pipestorage'
           backendAzureRmKey: 'pttr.tfstate'
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'apply'
           workingDirectory: $(ranjeet)
           environmentServiceNameAzureRM: $(anup_service_connection)